osx_image: xcode10.3
language: swift
script:
- fastlane scan
# Found simulator "iPhone 5s (12.2)"
#os: osx
#xcode_project: Numero.xcodeproj
#xcode_scheme: Numero
#xcode_destination: platform=iOS Simulator,OS=12.2,name=iPhone 8
